# Generated by Django 3.0.5 on 2020-06-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersistema_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersistema',
            name='conexion',
            field=models.BooleanField(default=False),
        ),
    ]
