# Generated by Django 3.0.6 on 2020-06-02 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0019_auto_20200507_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta_medica',
            name='atencion_medica',
            field=models.ForeignKey(db_column='id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Atencion_Medica'),
        ),
    ]
