# Generated by Django 3.0.6 on 2020-06-02 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0021_auto_20200601_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Nombre Comuna',
                'verbose_name_plural': 'Nombre Comunas',
                'db_table': 'nombre_comuna',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_estado', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo Estado',
                'verbose_name_plural': 'Tipo Estados',
                'db_table': 'tipo_estado',
            },
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id_formato', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_formato', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Nombre Formato',
                'verbose_name_plural': 'Nombre Formatos',
                'db_table': 'nombre_formato',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_genero', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo Genero',
                'verbose_name_plural': 'Tipo Generos',
                'db_table': 'tipo_genero',
            },
        ),
        migrations.CreateModel(
            name='Grupo_sanguineo',
            fields=[
                ('id_grupo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_grupo', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tipo Grupo Sanguineo',
                'verbose_name_plural': 'Tipo Grupo Sanguineos',
                'db_table': 'tipo_grupo',
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id_laboratorio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_laboratorio', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Nombre Laboratorio',
                'verbose_name_plural': 'Nombre Laboratorios',
                'db_table': 'nombre_laboratorio',
            },
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id_prevision', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_prevision', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tipo Previsión',
                'verbose_name_plural': 'Tipo Previsiones',
                'db_table': 'tipo_prevision',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id_sector', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_sector', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Nombre Sector',
                'verbose_name_plural': 'Nombre Sectores',
                'db_table': 'nombre_sector',
            },
        ),
        migrations.CreateModel(
            name='Unidad_medida',
            fields=[
                ('id_umedida', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_medida', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tipo Medida',
                'verbose_name_plural': 'Tipo Medidas',
                'db_table': 'tipo_medida',
            },
        ),
        migrations.RemoveField(
            model_name='recordatorio',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='recordatorio',
            name='id_medicamento',
        ),
        migrations.RemoveField(
            model_name='recordatorio',
            name='motivo',
        ),
        migrations.CreateModel(
            name='Cesfam',
            fields=[
                ('id_cesfam', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cesfam', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('id_comuna', models.ForeignKey(db_column='id_comuna', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Comuna')),
            ],
            options={
                'verbose_name': 'Nombre Cesfam',
                'verbose_name_plural': 'Nombre Cesfams',
                'db_table': 'nombre_cesfam',
            },
        ),
    ]
