# Generated by Django 3.0.6 on 2020-06-02 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0022_auto_20200601_2015'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cesfam',
            table='cesfam',
        ),
        migrations.AlterModelTable(
            name='comuna',
            table='comuna',
        ),
        migrations.AlterModelTable(
            name='estado',
            table='estado',
        ),
        migrations.AlterModelTable(
            name='formato',
            table='formato',
        ),
        migrations.AlterModelTable(
            name='genero',
            table='genero',
        ),
        migrations.AlterModelTable(
            name='grupo_sanguineo',
            table='grupo_sanguineo',
        ),
        migrations.AlterModelTable(
            name='laboratorio',
            table='laboratorio',
        ),
        migrations.AlterModelTable(
            name='prevision',
            table='prevision',
        ),
        migrations.AlterModelTable(
            name='sector',
            table='sector',
        ),
        migrations.AlterModelTable(
            name='unidad_medida',
            table='unidad_medida',
        ),
    ]
