# Generated by Django 3.0.6 on 2020-06-02 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0024_auto_20200601_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='email_familiar',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nro_familiar',
        ),
        migrations.AddField(
            model_name='carnet_paciente',
            name='id_cesfam',
            field=models.ForeignKey(db_column='id_cesfam', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Cesfam'),
        ),
        migrations.AddField(
            model_name='carnet_paciente',
            name='id_grupo',
            field=models.ForeignKey(db_column='id_grupo', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Grupo_sanguineo'),
        ),
        migrations.AddField(
            model_name='carnet_paciente',
            name='id_prevision',
            field=models.ForeignKey(db_column='id_prevision', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Prevision'),
        ),
        migrations.AddField(
            model_name='carnet_paciente',
            name='id_sector',
            field=models.ForeignKey(db_column='id_sector', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Sector'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='dosis',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='id_estado',
            field=models.ForeignKey(db_column='id_estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Estado'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='id_formato',
            field=models.ForeignKey(db_column='id_formato', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Formato'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='id_laboratorio',
            field=models.ForeignKey(db_column='id_laboratorio', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Laboratorio'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='id_umedida',
            field=models.ForeignKey(db_column='id_umedida', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Unidad_medida'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_comuna',
            field=models.ForeignKey(db_column='id_comuna', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Comuna'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_estado',
            field=models.ForeignKey(db_column='id_estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Estado'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_genero',
            field=models.ForeignKey(db_column='id_genero', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Genero'),
        ),
        migrations.AddField(
            model_name='recordatorio',
            name='celular_paciente',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recordatorio',
            name='celular_tutor',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recordatorio',
            name='email_paciente',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recordatorio',
            name='email_tutor',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recordatorio',
            name='estado_email',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recordatorio',
            name='estado_sms',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recordatorio',
            name='nombre_paciente',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
