# Generated by Django 3.0.6 on 2020-06-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0025_auto_20200601_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email_tutor',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nro_tutor',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
