# Generated by Django 3.0.6 on 2020-06-02 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0026_auto_20200601_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recordatorio',
        ),
    ]
