# Generated by Django 3.0.6 on 2020-06-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0027_delete_recordatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id_recordatorio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_medicamento', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('nombre_paciente', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email_paciente', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('celular_paciente', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('celular_tutor', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email_tutor', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('estado_sms', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('estado_email', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'db_table': 'recordatorio',
            },
        ),
    ]
