# Generated by Django 3.0.6 on 2020-06-02 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0028_recordatorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='total_disponible',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='total_reservado',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='total_retirado',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id_comuna',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id_estado',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id_genero',
        ),
    ]
