# Generated by Django 3.0.6 on 2020-06-02 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0029_auto_20200601_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='total_disponible',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='total_reservado',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='total_retirado',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_comuna',
            field=models.ForeignKey(db_column='id_comuna', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Comuna'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_estado',
            field=models.ForeignKey(db_column='id_estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Estado'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_genero',
            field=models.ForeignKey(db_column='id_genero', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Genero'),
        ),
    ]
