# Generated by Django 3.0.6 on 2020-06-02 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0030_auto_20200601_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento_entregado',
            name='cantidad_entregada',
        ),
        migrations.RemoveField(
            model_name='medicamento_entregado',
            name='id_medicamento_recetado',
        ),
    ]
