# Generated by Django 3.0.6 on 2020-06-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0032_medicamento_entregado_id_medicamento_recetado'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento_entregado',
            name='cantidad_entregada',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
