# Generated by Django 3.0.6 on 2020-06-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0033_medicamento_entregado_cantidad_entregada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cant_reservada',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_reserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_retiro',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_estado_reserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_medicamento_recetado',
        ),
    ]
