# Generated by Django 3.0.6 on 2020-06-02 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0034_auto_20200602_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='id_medicamento_recetado',
            field=models.ForeignKey(db_column='id_medicamento_recetado', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Medicamento'),
        ),
    ]
