# Generated by Django 3.0.6 on 2020-06-02 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0035_reserva_id_medicamento_recetado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cant_reservada',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_estado_reserva',
            field=models.ForeignKey(db_column='id_estado_reserva', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Estado_Reserva'),
        ),
    ]
