# Generated by Django 3.0.6 on 2020-06-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0036_auto_20200602_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cant_reservada',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_estado_reserva',
        ),
    ]
