# Generated by Django 3.0.6 on 2020-06-02 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0037_auto_20200602_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='id_estado_reserva',
            field=models.ForeignKey(db_column='id_estado_reserva', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Estado_Reserva'),
        ),
    ]
