# Generated by Django 3.0.6 on 2020-06-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0038_reserva_id_estado_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cant_reservada',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
