# Generated by Django 3.0.6 on 2020-06-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0039_reserva_cant_reservada'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_retiro',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
