# Generated by Django 3.0.6 on 2020-06-02 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0040_auto_20200602_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reposicion',
            name='cantidad_repuesta',
        ),
        migrations.RemoveField(
            model_name='reposicion',
            name='fecha_reposicion',
        ),
        migrations.RemoveField(
            model_name='reposicion',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='reposicion',
            name='nombre_farmaceutico',
        ),
    ]
