# Generated by Django 3.0.6 on 2020-06-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0041_auto_20200602_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='reposicion',
            name='cantidad_repuesta',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
