# Generated by Django 3.0.6 on 2020-06-02 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0042_reposicion_cantidad_repuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='reposicion',
            name='fecha_reposicion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reposicion',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reposicion',
            name='nombre_farmaceutico',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
