# Generated by Django 3.0.6 on 2020-06-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0043_auto_20200602_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordatorio',
            name='cesfam',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
