# Generated by Django 3.0.5 on 2020-06-22 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cestock', '0044_recordatorio_cesfam'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento_recetado',
            name='id_estado_reserva',
            field=models.ForeignKey(db_column='id_estado_reserva', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Estado_Reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id_medicamento_recetado',
            field=models.ForeignKey(db_column='id_medicamento_recetado', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cestock.Medicamento_Recetado'),
        ),
    ]
